force-app/main/default/objects/Character__c/Character__c.object-meta.xml
<CustomObject>
    <description>An Instance of a WoW Character.</description>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Character__c/fields/CharacterId__c.field-meta.xml
<CustomField>
    <fullName>CharacterId__c</fullName>
    <externalId>true</externalId>
    <label>CharacterId</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Character__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Druid</fullName>
            </value>
            <value>
                <fullName>Hunter</fullName>
            </value>
            <value>
                <fullName>Mage</fullName>
            </value>
            <value>
                <fullName>Paladin</fullName>
            </value>
            <value>
                <fullName>Priest</fullName>
            </value>
            <value>
                <fullName>Rogue</fullName>
            </value>
            <value>
                <fullName>Shaman</fullName>
            </value>
            <value>
                <fullName>Warlock</fullName>
            </value>
            <value>
                <fullName>Warrior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Character__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>KR</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Character__c/fields/Server__c.field-meta.xml
<CustomField>
    <fullName>Server__c</fullName>
    <label>Server</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>anathema</fullName>
            </value>
            <value>
                <fullName>amnennar</fullName>
            </value>
            <value>
                <fullName>arcanite reaper</fullName>
            </value>
            <value>
                <fullName>arugal</fullName>
            </value>
            <value>
                <fullName>ashkandi</fullName>
            </value>
            <value>
                <fullName>atiesh</fullName>
            </value>
            <value>
                <fullName>azuresong</fullName>
            </value>
            <value>
                <fullName>benediction</fullName>
            </value>
            <value>
                <fullName>bigglesworth</fullName>
            </value>
            <value>
                <fullName>blaumeux</fullName>
            </value>
            <value>
                <fullName>bloodsail buccaneers</fullName>
            </value>
            <value>
                <fullName>deviate delight</fullName>
            </value>
            <value>
                <fullName>earthfury</fullName>
            </value>
            <value>
                <fullName>faerlina</fullName>
            </value>
            <value>
                <fullName>fairbanks</fullName>
            </value>
            <value>
                <fullName>felstriker</fullName>
            </value>
            <value>
                <fullName>grobbulus</fullName>
            </value>
            <value>
                <fullName>heartseeker</fullName>
            </value>
            <value>
                <fullName>herod</fullName>
            </value>
            <value>
                <fullName>incendius</fullName>
            </value>
            <value>
                <fullName>kirtonos</fullName>
            </value>
            <value>
                <fullName>kromcrush</fullName>
            </value>
            <value>
                <fullName>kurinnaxx</fullName>
            </value>
            <value>
                <fullName>loatheb</fullName>
            </value>
            <value>
                <fullName>mankrik</fullName>
            </value>
            <value>
                <fullName>myzrael</fullName>
            </value>
            <value>
                <fullName>netherwind</fullName>
            </value>
            <value>
                <fullName>old blanchy</fullName>
            </value>
            <value>
                <fullName>pagle</fullName>
            </value>
            <value>
                <fullName>rattlegore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ranking__c/Ranking__c.object-meta.xml
<CustomObject>
    <label>Ranking</label>
    <nameField>
        <label>Boss Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ranking__c/fields/Character__c.field-meta.xml
<CustomField>
    <fullName>Character__c</fullName>
    <label>Character</label>
    <referenceTo>Character__c</referenceTo>
    <relationshipLabel>Rankings</relationshipLabel>
    <relationshipName>Rankings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Ranking__c/fields/Percentile__c.field-meta.xml
<CustomField>
    <fullName>Percentile__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Percentile</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Ranking__c/fields/Raid_Name__c.field-meta.xml
<CustomField>
    <fullName>Raid_Name__c</fullName>
    <label>Raid Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Naxxramas</fullName>
                <default>true</default>
                <label>Naxxramas</label>
            </value>
            <value>
                <fullName>Ahn&apos;Qiraj</fullName>
            </value>
            <value>
                <fullName>Blackwing Lair</fullName>
            </value>
            <value>
                <fullName>Molten Core</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ranking__c/fields/Rank_Total__c.field-meta.xml
<CustomField>
    <fullName>Rank_Total__c</fullName>
    <label>Rank Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ranking__c/fields/RankingId__c.field-meta.xml
<CustomField>
    <fullName>RankingId__c</fullName>
    <externalId>true</externalId>
    <label>RankingId</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Ranking__c/fields/Spec__c.field-meta.xml
<CustomField>
    <fullName>Spec__c</fullName>
    <defaultValue>&apos;DPS&apos;</defaultValue>
    <label>Spec</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ranking__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/characterController.cls
public class characterController {
	@AuraEnabled
    public static Character__c upsertCharacter(String cName, String cServer, String cRegion){
        List<JSON2Apex> rankingList = restTest.makeCallout(cName, cServer, cRegion);
        if(rankingList.size() > 0){
            List<Ranking__c> newRankings = new List<Ranking__c>();
            Character__c newCharacter = new Character__c();
            newCharacter.Name = cName;
            newCharacter.Server__c = cServer;
            newCharacter.Region__c = cRegion;
            newCharacter.Class__c = rankingList[0].class_Z;
            newCharacter.CharacterId__c = cName + '/'+ cServer + '/' + cRegion;
            System.debug(newCharacter);
            upsert newCharacter CharacterId__c;   
            for(JSON2Apex ranking: rankingList){
                Ranking__c newRank = new Ranking__c();
                newRank.Name = ranking.encounterName;
                newRank.Percentile__c = ranking.percentile;
                newRank.Raid_Name__c = 'Naxxramas';
                newRank.Rank__c = ranking.rank;
                newRank.Rank_Total__c = ranking.outOf;
                newRank.Spec__c = ranking.spec;
                newRank.Value__c = ranking.total;
                newRank.Character__c = newCharacter.Id;
                newRank.RankingId__c = ranking.encounterName + '/' + ranking.spec + '/' + newCharacter.CharacterId__c;
                newRankings.add(newRank);
            }
            System.debug(newRankings[0].Percentile__c);
            upsert newRankings RankingId__c;
            return newCharacter;
        }
        return null;
    }
    
    @AuraEnabled
    public static Character__c updateCharacterFromId(Id charId){
        Character__c uChar = [SELECT Id, Region__c, Server__c, Name FROM Character__c WHERE Id = :charId];
        return characterController.upsertCharacter(uChar.Name, uChar.Server__c, uChar.Region__c);
    }
}